version: '3.8'

services:
  db:
    image: postgres:15
    container_name: postgres_hotels
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: hotels
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: alberto12
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
